keys:
  - &users:
    - &bintang age1rgp5tfsaa6tw96h6eh7l4tdl6a2nsmgc854vgncc47sq4ytu8qkq3lc6p3
  - &hosts:
    - &barbatos age1v333uk8wm849lnegw4ra4pydlvgdqjn6fn288dd2a8fz2sdm0sys306qeq

creation_rules:
  - path_regex: systems/global/secrets.yaml$
    key_groups:
      - age:
        - *bintang
        - *barbatos
