keys:
  - &users:
    - &bintang age1rgp5tfsaa6tw96h6eh7l4tdl6a2nsmgc854vgncc47sq4ytu8qkq3lc6p3
  - &hosts:
    - &barbatos age1yz03wy9s2x8qlwytlqgsq38dn9z0vz6rfpxanp73lcdyh0650efs7f45lw

creation_rules:
  - path_regex: secrets/global/.*$
    key_groups:
      - age:
        - *bintang
        - *barbatos
  - path_regex: secrets/bintang/.*$
    key_groups:
      - age:
        - *bintang
        - *barbatos
