{
  imports = [
    ./anki.nix
    ./art.nix
    ./bottles.nix
    ./browser.nix
    ./distrobox.nix
    ./dolphin.nix
    ./electrum.nix
    ./entries.nix
    ./gplates.nix
    ./kitty.nix
    ./kooha.nix
    ./mime.nix
    ./mpv.nix
    ./obs.nix
    ./obsidian.nix
    ./office.nix
    ./qbittorrent.nix
    ./qgis.nix
    ./zathura.nix
  ];
}
